#!/usr/bin/env node
// ADR Logger — auto-captures [DECISION] tagged messages to docs/decisions.md
//
// Usable two ways:
//   1. Imported: import { adrLogDecision } from './adr-logger.js'
//   2. CLI:      node adr-logger.js --message-id <id> --project <path> --room <room>

import { getMessage, insertMessage, upsertAgent, closeDb as _closeDb, getOnlineAgents, projectHash } from '../lib/db.js';
import { touchSentinel } from '../lib/sentinel.js';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

// Canonical project: the ccchat-improve root (parent of the scripts/ dir)
const __dirname = dirname(fileURLToPath(import.meta.url));
export const CANONICAL_PROJECT = dirname(__dirname);

// --- Core functions ---

export function detectDecision(content) {
  // Only match [DECISION] at the very start of the message (trimmed),
  // or at the start of a line (after a newline). Never mid-sentence.
  const match = content.match(/(?:^|\n)[ \t*_>]*\[DECISION\][*_]*[ \t]*([\s\S]+)/i);
  return match ? match[1].trim() : null;
}

export function extractRejectedAlts(text) {
  const match = text.match(/rejected alternatives?:[ \t]*([^\n]+(?:\n[-*•][ \t]*[^\n]+)*)/i);
  if (match) {
    return match[1].trim().split(/\n[-*•][ \t]*/).map(s => s.trim()).filter(Boolean);
  }
  return [];
}

export function nextAdrId(decisionsPath) {
  if (!existsSync(decisionsPath)) return 1;
  const content = readFileSync(decisionsPath, 'utf8');
  const matches = [...content.matchAll(/^id:\s*ADR-(\d+)/gm)];
  if (matches.length === 0) return 1;
  return Math.max(...matches.map(m => parseInt(m[1], 10))) + 1;
}

export function writeAdr({ id, date, sessionId, author, decisionText, rejectedAlts, projectPath }) {
  const decisionsDir = join(projectPath, 'docs');
  const decisionsPath = join(decisionsDir, 'decisions.md');

  if (!existsSync(decisionsDir)) mkdirSync(decisionsDir, { recursive: true });

  const isNew = !existsSync(decisionsPath);
  const header = isNew ? '# Decision Log\n\nAuto-generated by ADR Logger. Each entry captures a [DECISION] tagged message.\n\n' : '';

  const altsBlock = rejectedAlts.length > 0
    ? rejectedAlts.map(a => `- ${a}`).join('\n')
    : '_None recorded — please update this entry_';

  const entry = `---
id: ADR-${id}
date: ${date}
session_id: ${sessionId}
author: ${author}
---

## Decision

${decisionText}

## Rejected Alternatives

${altsBlock}

## Rationale

_Optional — add context here if helpful_

`;

  if (isNew) {
    writeFileSync(decisionsPath, header + entry);
  } else {
    writeFileSync(decisionsPath, readFileSync(decisionsPath, 'utf8') + '\n' + entry);
  }

  return { decisionsPath, hasAlts: rejectedAlts.length > 0, id };
}

export function sendWarning(adrId, projectPath, room) {
  try {
    upsertAgent({ name: 'adr-logger', projectPath, currentRoom: room });
    insertMessage({
      type: 'system',
      fromAgent: 'adr-logger',
      fromProject: projectPath,
      room,
      content: `⚠️ ADR-${adrId} logged — but **rejected alternatives** field is blank. Edit \`docs/decisions.md\` to add at least one rejected alternative.`,
      metadata: { mentions: [], priority: 'normal' },
    });
    const myHash = projectHash(projectPath);
    for (const a of getOnlineAgents()) {
      if (a.name === 'adr-logger' && a.project_hash === myHash) continue;
      if (a.current_room !== room) continue;
      touchSentinel(a.project_hash, a.name);
    }
  } catch {
    // Warning is best-effort
  }
}

// --- Main exported function ---

export function adrLogDecision(msg, projectPath, room = 'general') {
  // Always write to the canonical shared project, not the sending agent's directory
  const targetProject = projectPath || CANONICAL_PROJECT;

  try {
    const decisionText = detectDecision(msg.content);
    if (!decisionText) return;

    const decisionsPath = join(targetProject, 'docs', 'decisions.md');
    const id = nextAdrId(decisionsPath);
    const rejectedAlts = extractRejectedAlts(decisionText);

    const { hasAlts } = writeAdr({
      id,
      date: msg.created_at || new Date().toISOString(),
      sessionId: msg.id,
      author: msg.from_agent,
      decisionText,
      rejectedAlts,
      projectPath: targetProject,
    });

    if (!hasAlts) {
      sendWarning(id, targetProject, room);
    }

    process.stderr.write(`adr-logger: wrote ADR-${id} to ${targetProject}/docs/decisions.md\n`);
  } catch (err) {
    process.stderr.write(`adr-logger: error: ${err.message}\n`);
  }
}

// --- CLI mode ---
const isCLI = process.argv[1] && process.argv[1].includes('adr-logger');
if (isCLI) {
  const args = process.argv.slice(2);
  function getFlag(name) {
    const idx = args.indexOf(`--${name}`);
    return idx !== -1 && idx + 1 < args.length ? args[idx + 1] : undefined;
  }

  const messageId = parseInt(getFlag('message-id'), 10);
  const projectPath = getFlag('project') || CANONICAL_PROJECT;
  const room = getFlag('room') || 'general';

  if (!messageId) {
    process.stderr.write('adr-logger: missing --message-id\n');
    process.exit(1);
  }

  try {
    const msg = getMessage(messageId);
    if (!msg) { process.stderr.write(`adr-logger: message ${messageId} not found\n`); process.exit(1); }
    adrLogDecision({ content: msg.content, id: msg.id, created_at: msg.created_at, from_agent: msg.from_agent }, projectPath, room);
  } finally {
    _closeDb();
  }
}
